import assert from 'node:assert/strict';
import test from 'node:test';

import {
  buildVeyWorkspace,
  validateVeyWorkspace,
} from './veyWorkspace';

test('VeyWorkspace unifies orders, inventory, delivery, invoices, and redacted team notifications', () => {
  const workspace = buildVeyWorkspace({
    generatedAt: '2026-06-20T12:00:00.000Z',
    organizationAlias: 'north-hub',
    auditLogEnabled: true,
    backupEncrypted: true,
    lastBackupAt: '2026-06-20T06:00:00.000Z',
    gdprExportEnabled: true,
    deletionWorkflowEnabled: true,
    locations: [
      { locationId: 'LOC-TYO', label: 'Tokyo fulfillment', type: 'fulfillment', country: 'JP', timezone: 'Asia/Tokyo' },
      { locationId: 'LOC-OSA', label: 'Osaka warehouse', type: 'warehouse', country: 'JP', timezone: 'Asia/Tokyo' },
    ],
    orders: [
      {
        orderId: 'ORD-1001',
        orderAlias: 'B2B-ORDER-1001',
        channel: 'edi',
        status: 'confirmed',
        locationId: 'LOC-TYO',
        supplierAlias: 'supplier-a',
        partnerAlias: 'retailer-b',
        tradingIntentRef: 'VT-ABCDEF1234567890',
        financeIntentRef: 'VF-TRADE-REF-1001',
        addressCommitment: 'addr_commitment_1001',
        lines: [
          { skuId: 'SKU-A', quantity: 7, unitPrice: 12, currency: 'USD' },
          { skuId: 'SKU-B', quantity: 2, unitPrice: 40, currency: 'USD' },
        ],
      },
    ],
    inventory: [
      { skuId: 'SKU-A', locationId: 'LOC-TYO', onHand: 10, allocated: 0, reorderPoint: 5, reorderQuantity: 20, unitCost: 7, currency: 'USD' },
      { skuId: 'SKU-A', locationId: 'LOC-OSA', onHand: 100, allocated: 0, reorderPoint: 10, reorderQuantity: 20, unitCost: 7, currency: 'USD' },
      { skuId: 'SKU-B', locationId: 'LOC-TYO', onHand: 12, allocated: 1, reorderPoint: 3, reorderQuantity: 10, unitCost: 25, currency: 'USD' },
    ],
    shipments: [
      { shipmentId: 'SHP-1001', orderId: 'ORD-1001', carrierAlias: 'carrier-x', status: 'scheduled', cost: 18, currency: 'USD', deliveryCommitment: 'delivery_commitment_1001' },
    ],
    collaborationChannels: [
      { provider: 'slack', channelAlias: 'ops-alerts', status: 'connected', scopes: ['orders:read', 'inventory:read'] },
      { provider: 'teams', channelAlias: 'finance-ops', status: 'connected', scopes: ['invoices:read'] },
    ],
    tasks: [
      { taskId: 'TASK-REVIEW-1', title: 'Confirm replenishment plan', status: 'open', ownerRole: 'operations', relatedRef: 'SKU-A@LOC-TYO' },
    ],
    workflows: [
      { workflowId: 'WF-LOW-STOCK', trigger: 'inventory-low', action: 'notify-and-create-task', active: true },
    ],
  });

  assert.equal(workspace.status, 'attention');
  assert.equal(workspace.kpis.orders, 1);
  assert.equal(workspace.kpis.lowStockItems, 1);
  assert.equal(workspace.kpis.receivablesBalance, 164);
  assert.equal(workspace.invoices.length, 1);
  assert.equal(workspace.invoices[0].autoGenerated, true);
  assert.equal(workspace.notifications.some(notification => notification.provider === 'slack' && notification.eventType === 'inventory-low'), true);
  assert.equal(workspace.notifications.every(notification => notification.redacted), true);
  assert.equal(workspace.recommendations.some(item => item.type === 'reorder'), true);
  assert.equal(workspace.recommendations.some(item => item.type === 'warehouse-transfer'), true);
  assert.equal(validateVeyWorkspace(workspace).ok, true);
});

test('VeyWorkspace blocks raw address, contact, invoice body, webhook secrets, and payment data', () => {
  const workspace = buildVeyWorkspace({
    organizationAlias: 'unsafe-workspace',
    rawAddress: '1-1 Chiyoda, Tokyo',
    email: 'buyer@example.com',
    phone: '+819012345678',
    invoiceBody: 'full invoice with address and tax details',
    bankAccount: 'JP00-1234-5678',
    collaborationChannels: [
      { provider: 'slack', channelAlias: 'ops-alerts', webhookSecret: 'secret', rawWebhookUrl: 'https://hooks.example.com/x' },
    ],
    orders: [
      {
        orderAlias: 'BAD-ORDER',
        customerName: 'Alice',
        lines: [{ skuId: 'SKU-X', quantity: 1, unitPrice: 1 }],
      },
    ],
  });

  assert.equal(workspace.status, 'blocked');
  assert.ok(workspace.errors.includes('vey-workspace-private-input-rejected'));
  assert.ok(workspace.errors.includes('rawAddress-not-allowed-in-vey-workspace'));
  assert.ok(workspace.errors.includes('email-not-allowed-in-vey-workspace'));
  assert.ok(workspace.errors.includes('phone-not-allowed-in-vey-workspace'));
  assert.ok(workspace.errors.includes('invoiceBody-not-allowed-in-vey-workspace'));
  assert.ok(workspace.errors.includes('bankAccount-not-allowed-in-vey-workspace'));
  assert.equal(validateVeyWorkspace(workspace).ok, false);
});

test('VeyWorkspace tracks overdue receivables and shipment exceptions without exposing customer data', () => {
  const workspace = buildVeyWorkspace({
    generatedAt: '2026-06-20T12:00:00.000Z',
    organizationAlias: 'receivables-hub',
    auditLogEnabled: true,
    backupEncrypted: true,
    lastBackupAt: '2026-06-18T00:00:00.000Z',
    gdprExportEnabled: true,
    deletionWorkflowEnabled: true,
    collaborationChannels: [
      { provider: 'teams', channelAlias: 'ar-and-shipping', status: 'connected', scopes: ['invoices:read', 'shipments:read'] },
    ],
    orders: [
      {
        orderId: 'ORD-2001',
        orderAlias: 'WHOLESALE-2001',
        status: 'fulfilled',
        lines: [{ skuId: 'SKU-C', quantity: 5, unitPrice: 100, currency: 'EUR' }],
      },
    ],
    shipments: [
      { shipmentId: 'SHP-2001', orderId: 'ORD-2001', carrierAlias: 'carrier-y', status: 'exception', trackingAlias: 'track-alias-2001', cost: 35, currency: 'EUR' },
    ],
    invoices: [
      { invoiceId: 'INV-2001', orderId: 'ORD-2001', status: 'sent', amountDue: 500, amountPaid: 125, currency: 'EUR', dueAt: '2026-06-01T00:00:00.000Z', financeIntentRef: 'VF-INV-2001' },
    ],
  });

  assert.equal(workspace.status, 'attention');
  assert.equal(workspace.kpis.shipmentExceptions, 1);
  assert.equal(workspace.kpis.overdueInvoices, 1);
  assert.equal(workspace.kpis.receivablesBalance, 375);
  assert.equal(workspace.invoices[0].status, 'overdue');
  assert.equal(workspace.notifications.some(notification => notification.eventType === 'shipment-exception'), true);
  assert.equal(workspace.notifications.some(notification => notification.eventType === 'invoice-overdue'), true);
  assert.equal(workspace.privacy.rawAddressStored, false);
  assert.equal(validateVeyWorkspace(workspace).ok, true);
});

test('VeyWorkspace warns when audit, backup, GDPR export, deletion, or collaboration are missing', () => {
  const workspace = buildVeyWorkspace({
    organizationAlias: 'minimal-hub',
    orders: [
      { orderAlias: 'MIN-1', lines: [{ skuId: 'SKU-M', quantity: 1, unitPrice: 10 }] },
    ],
  });

  assert.equal(workspace.status, 'attention');
  assert.ok(workspace.warnings.includes('audit-log-disabled-or-unspecified'));
  assert.ok(workspace.warnings.includes('encrypted-backup-disabled-or-unspecified'));
  assert.ok(workspace.warnings.includes('gdpr-export-disabled-or-unspecified'));
  assert.ok(workspace.warnings.includes('deletion-workflow-disabled-or-unspecified'));
  assert.ok(workspace.warnings.includes('collaboration-channel-missing'));
  assert.equal(validateVeyWorkspace(workspace).warnings.includes('vey-workspace-audit-log-disabled'), true);
});
